# Generated by Django 2.2.4 on 2019-11-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_result', models.FileField(upload_to='composite-image/%Y/%m/%d')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Body')),
                ('clothe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Clothe')),
            ],
        ),
    ]
