# Generated by Django 2.2.4 on 2019-12-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('composite_image', models.FileField(upload_to='composite-image/%Y/%m/%d')),
                ('score', models.CharField(max_length=10)),
                ('body_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.BodyImage')),
                ('clothe_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.ClotheImage')),
            ],
        ),
    ]
