# Generated by Django 2.2.4 on 2019-11-17 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('change', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositeimage',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Body'),
        ),
        migrations.AddField(
            model_name='compositeimage',
            name='clothe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Clothe'),
        ),
    ]
