# Generated by Django 2.2.6 on 2019-12-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositeimage',
            name='score',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
